### ISSUE TITLE
Refactor folder structure to be package-oriented

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#18]
## Package Names

First, we need to decide on the terminology. The table below shows the terminology for this the various packages we support.

| Package Management System | Package Format | Package Repository/Host |
|--------	|--------	|-----------------	|
| Maven 	| JAR 	| Maven Central 	|
| PIP 	| ? 		| PyPI 			|
| NPM 	| ? 		| NPM 			|
| APT 	| DEB 	| (decentralised) 	|
| RPM 	| RPM 	| (decentralised) 	|
| Brew	| ?		| Brew			|
| GitHub  | ?            | GitHub                 |

We need to fill in the `?` above, and Docker is also an anomaly here because it's not really a "package manager". However, I think we should stick with a consistent style of naming. In this case, let's go with the first column ("Package Manager") as the canonical names. E.g. don't use "deb" as a package name, nor should you use "pypi".  Wherever the package format is expected, we should use the second column ("Package Format").

## Component Names

We need to determine the components of "distribution", which is ultimately comprised of two steps:
- `assembly`: the task of "building" the distribution
- `deployment`: the task of "uploading" the distribution

If one of the packages do not have one of the steps, e.g. no `assemble` step, then that component can just be omitted. 

---

Project Structure:
```
common
  - assemble_targz
  - assemble_zip
apt
  - assemble_apt
  - deploy_apt
brew
  - deploy_brew
github
  - deploy_github
maven
  - assemble_maven
  - deploy_maven
npm
  - assemble_npm
  - deploy_npm
pip
  - assemble_pip
  - deploy_pip
rpm
  - assemble_rpm
  - deploy_rpm
```

**Comment by lolski** [comment]
@vmax Let's review the `distribution` module and split them as per the description above in order to have a more meaningful architecture.

Additionally, the Github should have a rule `deploy_github`.

**Comment by haikalpribadi** [comment]
@vmax and @lolski note that I have replaced the term `distribution` to `assembly` in the proposed structure above. The reason being:
1. This repo is already called "Distribution", so we need to think of a better name for the subfolders.
2. We can see now that "distribution" is ultimately comprised of two tasks:
    a) The task of "building" the distribution
    b) The task of "uploading" the distribution

Given the two reasons above, I think a good set of terminology for us to stick with is:
- `distribution` which is comprised of two steps:
    * `assembly`: the task of "building" the distribution
    * `deployment`: the task of "uploading" the distribution

Sounds good?

Please make sure we use this terminology consistently across all repositories and codebase.

**Comment by haikalpribadi** [comment]
alternatively, we can also go with `assemble` and `deploy` - in contrast to - `assembly` and `deployment`.

**Comment by lolski** [comment]
@haikalpribadi sounds good, the name makes sense. I like `assemble` and `deploy`

**Comment by haikalpribadi** [comment]
yeah `assemble` and `deploy` also goes well with the rule names, e.g. `assemble_maven[_jar]`, `assemble_apt[_deb]`, `deploy_maven[_jar]` and `deploy_apt[_deb]`

**Comment by haikalpribadi** [comment]
We also need to be consistent in naming the packages, @lolski @vmax. First let's review all the different variations of the names:

| Package Manager | Package Format | Package Repository/Host |
|--------	|--------	|-----------------	|
| Maven 	| JAR 	| Maven Central 	|
| PIP 	| ? 		| PyPI 			|
| NPM 	| ? 		| NPM 			|
| APT 	| DEB 	| (decentralised) 	|
| RPM 	| RPM 	| (decentralised) 	|
| Docker 	| ? 		| Docker Hub 		|

We need to fill in the `?` above. And Docker is also an anomaly here because it's not really a "package manager".

However, I think we should stick with a consistent style of naming. In this case, let's go with the first column ("Package Manager") as the canonical names. E.g. don't use "deb" as a package name, nor should you use "pypi". 

Wherever the package format is expected, we should use the second column ("Package Format").

I've updated the description for this issue above. But we also need to propagate this change across all the Bazel rule names. Should I make a table for the rule names too?

**Comment by vmax** [comment]
follow-up: graknlabs/bazel-distribution#44
