### ISSUE TITLE
Question: implications of Packer in Bazel?

### ISSUE THREAD

**Issue by njlr** [graknlabs/bazel-distribution#203]
My understanding of Packer is that it can register AMIs to AWS so that you can deploy them as EC2s. This sits outside of Bazel's usual design (all inputs are local, and all outputs go to the artefacts folder). 

What are the implications of a Bazel rule that might modify external services (in this case AWS) in practice?

**Comment by vmax** [comment]
@njlr thank you for your question!

We architected the rules wrapping Packer (and pretty much all rules, for that matter) as a combination of `assemble_` rule and `deploy_` rule. Assemble rules are meant to be built by executing `bazel build` and deployment rules are meant to be executed via `bazel run` and usually depend on revelant assemble target. With regards to Packer, `assemble_packer` rule would only produce an archive on files Packer would need to run, so no "real" action (touching the network) would happen is you build it. The real image deployment happens when you execute `bazel run` on a `deploy_packer` target.

**Comment by njlr** [comment]
@vmax That makes sense. Thank you!
