### ISSUE TITLE
A release DEB package must follow naming conventions

### ISSUE THREAD

**Issue by lolski** [graknlabs/bazel-distribution#46]
Based on [The Debian FAQ](https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics#s-pkgname), a package should be named in this convention:
```
<foo>_<VersionNumber>-<DebianRevisionNumber>_<DebianArchitecture>.deb
```

In order to accomodate the change, `distribution_deb` rule should take in an additional parameters, `debian_revision_number` and `debian_architecture`.

**Comment by vmax** [comment]
Closing this issue because of these considerations:

- It's not possible to dynamically read version from version file
- It's sufficient for the developer to be able to distinguish packages by filename (`grakn-core-bin` vs `grakn-core-server` vs `grakn-core-console`
- Sonatype renames files on upload so they have expected & valid structure. You don't have control over it, regardless of how you name file to upload.
